<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Megan Hessel">
<meta name="dcterms.date" content="2026-01-26">

<title>🌬️🗳 Assignment 2: Wind Turbines, Matching, and Difference-in-Differences</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="HW2_START_files/libs/clipboard/clipboard.min.js"></script>
<script src="HW2_START_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="HW2_START_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="HW2_START_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="HW2_START_files/libs/quarto-html/popper.min.js"></script>
<script src="HW2_START_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="HW2_START_files/libs/quarto-html/anchor.min.js"></script>
<link href="HW2_START_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="HW2_START_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="HW2_START_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="HW2_START_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="HW2_START_files/libs/bootstrap/bootstrap-aff6bd71cf38ce7a6494770b00151a6f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">🌬️🗳 Assignment 2: Wind Turbines, Matching, and Difference-in-Differences</h1>
<p class="subtitle lead">Replicate causal inference identification strategies in Stokes (2015)</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Megan Hessel </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 26, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="assignment-instructions" class="level3">
<h3 class="anchored" data-anchor-id="assignment-instructions">Assignment instructions</h3>
<p>Working with classmates to troubleshoot code and concepts is encouraged. If you collaborate, list collaborators at the top of your submission.</p>
<p>All written responses must be written independently (in your own words).</p>
<p>Keep your work readable: Use clear headings and label plot elements thoughtfully.</p>
<p>Assignment submission: <u>Megan Hessel</u></p>
<hr>
</section>
<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p>In this assignment I will be doing political weather forecasting except the “storms” I care about are electoral swings that might follow local wind turbine development.</p>
<p>In Stokes (2015), the idea is that a policy with diffuse benefits (cleaner electricity) can create concentrated local costs (turbines nearby), and those local opponents may “send a signal” at the ballot box (i.e., NIMBYISM). Your job is to use two statistical tools:</p>
<ul>
<li>Matching: Can we create a more apples-to-apples comparison between precincts that did vs.&nbsp;did not end up near turbine proposals?</li>
<li>Fixed effects + Difference-in-Differences: Can we use repeated elections to estimate how within-precinct changes in turbine exposure relate to changes in incumbent vote share?</li>
</ul>
<hr>
</section>
<section id="this-repo-is-replicating-the-matching-and-fixed-effects-analyses-from-study" class="level3">
<h3 class="anchored" data-anchor-id="this-repo-is-replicating-the-matching-and-fixed-effects-analyses-from-study">This repo is replicating the matching and fixed effects analyses from study:</h3>
<blockquote class="blockquote">
<p>Stokes (2015): <em>“Electoral Backlash against Climate Policy: A Natural Experiment on Retrospective Voting and Local Resistance to Public Policy</em>.</p>
</blockquote>
<ul>
<li><strong>Study:</strong> <a href="https://drive.google.com/file/d/1y2Okzjq2EA43AW5JzCvFS8ecLpeP6NKh/view?usp=sharing">Stokes (2015) - Article</a></li>
<li><strong>Data source:</strong> <a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/SDUGCC">Dataverse-Stokes2015</a></li>
</ul>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><code>NOTE:</code> Replication of study estimates will be approximate. An alternative matching procedure and fixed effects estimation package are utilized in this assignment for illustration purposes.</p>
</div>
</div>
</div>
<hr>
</section>
<section id="setup-load-libraries" class="level3">
<h3 class="anchored" data-anchor-id="setup-load-libraries">Setup: Load libraries</h3>
<ol start="0" type="1">
<li>Load libraries (+ install if needed)</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jtools)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gtsummary)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MatchIt) <span class="co"># matching</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cobalt)  <span class="co"># balance + love plots</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fixest) <span class="co"># fast fixed effects</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales) <span class="co"># plotting</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<hr>
</section>
<section id="part-1-study-background" class="level3">
<h3 class="anchored" data-anchor-id="part-1-study-background">Part 1: Study Background</h3>
<section id="a.-dive-into-the-details-of-the-study-design-and-evaluation-plan" class="level4">
<h4 class="anchored" data-anchor-id="a.-dive-into-the-details-of-the-study-design-and-evaluation-plan"><strong>1A.</strong> Dive into the details of the study design and evaluation plan</h4>
<blockquote class="blockquote">
<p>Goal: Get familiar with the study setting, environmental issue, and policy under evaluation.</p>
</blockquote>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><code>NOTE:</code> Read over study to inform your response to the assignment questions. For this assignment we will skip-over sections that describe the <em>Instrumental Variables</em> identification strategy. We will cover instrumental variable designs weeks 6-7.</p>
</div>
</div>
</div>
<p><strong>1A.Q1</strong> Summarize the environmental policy issue, the outcome of interest, and the intervention being evaluated. Be sure to include a brief description of each of the following key elements of the study: unit of analysis, outcome, treatment, comparison group):</p>
<ul>
<li><p>The centrist Liberal Party created a “feed-in tariff” (FIT) policy in the early 2000s to phase-out coal by subsidizing new, low-carbon technologies (ie wind). In 2009, a law passed that removed local veto power in renewable energy placement. The “not in my backyard” (NIMBY) thought process may have caused local voting to push the Liberal Party out of the government in the 2011 election. This, this study investigates if proximity to wind energy (intervention/treatment) impacted voting behaviors (outcome) with fixed effects estimators and instrumental variable estimators. To do this, Stokes studied the electoral precincts (average ~350 voters each) within the 26 districts.</p>
<ul>
<li><p>Treatment: precincts that had a proposed or operational wind turbine within its boundaries</p></li>
<li><p>Control: precincts without wind turbines</p></li>
<li><p>Outcome: Liberal Party vote in provincial elections (2003, 2007, 2011)</p></li>
</ul></li>
</ul>
<p><strong>1A.Q2</strong> Why might turbine proposals be correlated with baseline political preferences or rural areas? Provide 2 plausible mechanisms, and explain why that creates confounding.</p>
<ul>
<li><p>Wind turbines need open, unobstructive land to be effective. Therefore, wind turbine ideal placement is in rural areas. However, the baseline political preferences in rural communities tends to be more conservative, who would vote against the Liberal Party pre and post the FIT policy (the intervention). Studying the <em>change</em> in voting behavior in these communities is faulty and confounded since the people dealing with the treatment (wind turbines) have a continual pre-existing preferences against the treatment.</p></li>
<li><p>Before 2009 (when the law to remove local veto power), poorer communities most likely disproportional faced the burden of renewable energy construction. Wealthier, more urban communities have a greater ability to resist and/or block turbine proposals due to more money, power, time, and easier communication. Thus, wind turbine placement could be disproportionally placed in poorer communities which would already a pre-existing baseline political preferences.</p></li>
<li><p>These confounding variables impact the outcome, creating a fundamental problem in the study as treatment assignment is not randomized.</p></li>
</ul>
<hr>
</section>
<section id="b.-break-down-the-causal-inference-strategy-and-identify-threats-to-identification" class="level4">
<h4 class="anchored" data-anchor-id="b.-break-down-the-causal-inference-strategy-and-identify-threats-to-identification"><strong>1B.</strong> Break down the causal inference strategy and identify threats to identification:</h4>
<p><strong>1B.Q1</strong> What is the key identifying assumption for a fixed effects / Difference-in-Difference design? Explain how this assumption when satisfied provides evidence of causal effect:</p>
<ul>
<li><p>Assumption: Parallel trends! Prior to the intervention, the treatment and control group must have similar trends in the voting behavior.</p></li>
<li><p>If the 2 groups are similar in there voting behaviors pre-intervention, it is save to assume the treatment group’s counter factual would follow the control group trends. Parallel trends create a realistic counter factual we can use to understand intervention effects.</p></li>
</ul>
<p><strong>1B.Q2</strong> What is the reason for using a fixed effects approach from a causal inference perspective? Summarize within the context of study (in your own words).</p>
<ul>
<li>From a causal inference perspective, fix effects remove omitted variable bias from time-invariant factors and remove between group variation. The fixed effect approach controls for any pre-exiting political or rural baseline beliefs, studing the change in voting shares within the precincts after intervention.</li>
</ul>
<p><strong>1B.Q3</strong> What part of the SUTVA assumption is most likely violated in the context of this study design (and why)?</p>
<ul>
<li>SUTVA has 2 main assumptions: no interference and consistency. No interference means each treatment effect in one precincts would not effect the other. However, political voting behavior typically has active engagement within and between communities. Stokes discuss the protests and campaign events against the Liberal Party. Therefore, one community beliefs can easily effect and empower other precincts outcomes. SUTVA’s consistency assumption means each treatment must be administered consistently to all treatment groups. Yet, treatment groups can have variable proposed or operational wind turbines due to differences in space. Hence, both SUTVA assumptions are violated.</li>
</ul>
<p><strong>1B.Q4</strong> Why does spillover matter when estimating an unbiased treatment effect?</p>
<ul>
<li>In a perfect world, control and treatment groups would be un-affected by each other. However, this rarely is possible. Because of communication and interactions between communities, precincts actions can impact each other. This interaction and influence cause bias in treatment effect because it creates new confounding variables that effect outcomes in both groups.</li>
</ul>
<p><strong>1B.Q5</strong> How do the authors assess the risk of spillovers, and what analytic choice do they make to attempt to mitigate the risk that spillover biases the causal estimate?</p>
<ul>
<li>In this study, spillover is due to the enormous wind turbines that can be seen in neighboring communities. To reduce the spillover treatment bias, Stoke studied voting behaviors in relation to distance from the turbines, creating 6km buffers that excludes these communities from the control group.</li>
</ul>
<hr>
</section>
</section>
<section id="part-2-matching" class="level3">
<h3 class="anchored" data-anchor-id="part-2-matching">Part 2: Matching</h3>
<hr>
<p>We will start by evaluating the 2007 survey (cross-sectional) data. Treatment is defined by whether a precinct is near a turbine proposal (within 3 km).</p>
<blockquote class="blockquote">
<p>Goal: Match precincts using pre-treatment covariates and then estimate the effect of proposed wind turbines on incumbent vote share.</p>
</blockquote>
<section id="a.-load-data-for-matching" class="level4">
<h4 class="anchored" data-anchor-id="a.-load-data-for-matching"><strong>2A.</strong> Load data for matching</h4>
<ol type="1">
<li>Read in data file <code>stokes15_survey2007.csv</code></li>
<li>Code <code>precinct_id</code> and <code>district_id</code> as factors</li>
<li>Take a look at the data</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load in data </span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>match_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"stokes15_survey2007.csv"</span>))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Change cols to factors </span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>match_data<span class="sc">$</span>precinct_id <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(match_data<span class="sc">$</span>precinct_id)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>match_data<span class="sc">$</span>district_id <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(match_data<span class="sc">$</span>district_id)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Look at the data </span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(match_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 16
  precinct_id  district_id change_liberal proposed_turbine_3km log_wind_power
  &lt;fct&gt;        &lt;fct&gt;                &lt;dbl&gt;                &lt;dbl&gt;          &lt;dbl&gt;
1 10.001.10.1. 10                  0.0846                    0           6.65
2 10.002.10.1. 10                  0.132                     0           6.30
3 10.003.10.2. 10                  0.182                     0           6.31
4 10.004.10.1. 10                  0.154                     0           6.65
5 10.005.10.3. 10                  0.0588                    0           6.10
6 10.006.10.2. 10                  0.134                     0           6.65
# ℹ 11 more variables: log_home_val_07 &lt;dbl&gt;, p_uni_degree &lt;dbl&gt;,
#   log_median_inc &lt;dbl&gt;, log_pop_denc &lt;dbl&gt;, mindistlake &lt;dbl&gt;,
#   mindistlake_sq &lt;dbl&gt;, longitude &lt;dbl&gt;, long_sq &lt;dbl&gt;, latitude &lt;dbl&gt;,
#   lat_sq &lt;dbl&gt;, long_lat &lt;dbl&gt;</code></pre>
</div>
</div>
<p><strong>2A.Q1</strong> Intuition check: <strong>Why match?</strong> Explain rationale for using this method.</p>
<ul>
<li>Due to confounding variables, there is pre-existing differences in the groups. Matching chooses communities that are similar, so treatment and control groups are homogeneous. This reduces the bias between the treatment and control groups.</li>
</ul>
<hr>
</section>
<section id="b.-check-imbalance-before-matching" class="level4">
<h4 class="anchored" data-anchor-id="b.-check-imbalance-before-matching"><strong>2B.</strong> Check imbalance (before matching)</h4>
<ul>
<li>Create a covariate <em>balance table</em> comparing treated and control precincts</li>
<li>Treatment indicator: <code>proposed_turbine_3km</code></li>
<li>Include pre-treatment covariates: <code>log_home_val_07</code>, <code>p_uni_degree</code>, <code>log_median_inc</code>, <code>log_pop_denc</code></li>
<li>Use the <code>tbl_summary()</code> function from the <code>{gtsummary}</code> package.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>match_data <span class="sc">%&gt;%</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>( <span class="co"># select column we want to compare </span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>        log_home_val_07, p_uni_degree, log_median_inc, log_pop_denc, proposed_turbine_3km</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tbl_summary</span> ( <span class="co"># Create balance table </span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">by =</span> proposed_turbine_3km, </span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">statistic =</span> <span class="fu">list</span>(</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>            <span class="fu">all_continuous</span>() <span class="sc">~</span> <span class="st">"{mean} ({sd})"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>            <span class="fu">all_categorical</span>() <span class="sc">~</span> <span class="st">"{n} ({p}%)"</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    )) <span class="sc">%&gt;%</span>  <span class="co"># modify headers </span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">modify_header</span>(label <span class="sc">~</span> <span class="st">"**Covariate**"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">modify_spanning_header</span>(<span class="fu">c</span>(<span class="st">"stat_1"</span>, <span class="st">"stat_2"</span>) <span class="sc">~</span> <span class="st">"**Group**"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fwqdnhwqyp" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#fwqdnhwqyp table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#fwqdnhwqyp thead, #fwqdnhwqyp tbody, #fwqdnhwqyp tfoot, #fwqdnhwqyp tr, #fwqdnhwqyp td, #fwqdnhwqyp th {
  border-style: none;
}

#fwqdnhwqyp p {
  margin: 0;
  padding: 0;
}

#fwqdnhwqyp .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#fwqdnhwqyp .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#fwqdnhwqyp .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#fwqdnhwqyp .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#fwqdnhwqyp .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#fwqdnhwqyp .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#fwqdnhwqyp .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#fwqdnhwqyp .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#fwqdnhwqyp .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#fwqdnhwqyp .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#fwqdnhwqyp .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#fwqdnhwqyp .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#fwqdnhwqyp .gt_spanner_row {
  border-bottom-style: hidden;
}

#fwqdnhwqyp .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#fwqdnhwqyp .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#fwqdnhwqyp .gt_from_md > :first-child {
  margin-top: 0;
}

#fwqdnhwqyp .gt_from_md > :last-child {
  margin-bottom: 0;
}

#fwqdnhwqyp .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#fwqdnhwqyp .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#fwqdnhwqyp .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#fwqdnhwqyp .gt_row_group_first td {
  border-top-width: 2px;
}

#fwqdnhwqyp .gt_row_group_first th {
  border-top-width: 2px;
}

#fwqdnhwqyp .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#fwqdnhwqyp .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#fwqdnhwqyp .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#fwqdnhwqyp .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#fwqdnhwqyp .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#fwqdnhwqyp .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#fwqdnhwqyp .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#fwqdnhwqyp .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#fwqdnhwqyp .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#fwqdnhwqyp .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#fwqdnhwqyp .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#fwqdnhwqyp .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#fwqdnhwqyp .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#fwqdnhwqyp .gt_left {
  text-align: left;
}

#fwqdnhwqyp .gt_center {
  text-align: center;
}

#fwqdnhwqyp .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#fwqdnhwqyp .gt_font_normal {
  font-weight: normal;
}

#fwqdnhwqyp .gt_font_bold {
  font-weight: bold;
}

#fwqdnhwqyp .gt_font_italic {
  font-style: italic;
}

#fwqdnhwqyp .gt_super {
  font-size: 65%;
}

#fwqdnhwqyp .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#fwqdnhwqyp .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#fwqdnhwqyp .gt_indent_1 {
  text-indent: 5px;
}

#fwqdnhwqyp .gt_indent_2 {
  text-indent: 10px;
}

#fwqdnhwqyp .gt_indent_3 {
  text-indent: 15px;
}

#fwqdnhwqyp .gt_indent_4 {
  text-indent: 20px;
}

#fwqdnhwqyp .gt_indent_5 {
  text-indent: 25px;
}

#fwqdnhwqyp .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#fwqdnhwqyp div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="gt_col_headings gt_spanner_row header">
<th rowspan="2" id="label" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Covariate</strong></th>
<th colspan="2" id="level 1; stat_1" class="gt_center gt_columns_top_border gt_column_spanner_outer" data-quarto-table-cell-role="th" scope="colgroup"><div class="gt_column_spanner">
<strong>Group</strong>
</div></th>
</tr>
<tr class="gt_col_headings even">
<th id="stat_1" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>0</strong><br>
N = 5,619<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="stat_2" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>1</strong><br>
N = 354<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">log_home_val_07</td>
<td class="gt_row gt_center" headers="stat_1">12.26 (0.37)</td>
<td class="gt_row gt_center" headers="stat_2">12.29 (0.29)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">p_uni_degree</td>
<td class="gt_row gt_center" headers="stat_1">0.17 (0.12)</td>
<td class="gt_row gt_center" headers="stat_2">0.13 (0.09)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">log_median_inc</td>
<td class="gt_row gt_center" headers="stat_1">10.32 (0.22)</td>
<td class="gt_row gt_center" headers="stat_2">10.31 (0.19)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">log_pop_denc</td>
<td class="gt_row gt_center" headers="stat_1">5.12 (2.40)</td>
<td class="gt_row gt_center" headers="stat_2">3.54 (1.78)</td>
</tr>
</tbody><tfoot>
<tr class="gt_footnotes odd">
<td colspan="3" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> Mean (SD)</td>
</tr>
</tfoot>

</table>

</div>
</div>
</div>
<p><strong>2B.Q1</strong> Summarize the table output: Which covariates look balanced/imbalanced?</p>
<ul>
<li>All covariates look pretty balanced. The covariate with the largest difference between control and treatment is the <code>log_pop_denc</code>. But <code>log_pop_denc</code> also has a large standard deviation, so there is not much of an imbalance.</li>
</ul>
<p><strong>2B.Q2</strong> Describe in your own words why these covariates might be expected to confound the treatment estimate:</p>
<ul>
<li>These covariates relate to economic status and home location (rural vs urban) which are all confounding variables (discussed in <strong>1A.Q2</strong>) possibly impacting the communities voting behavior.</li>
</ul>
<hr>
<p><strong>2B.Q3</strong> Intuition check: What type of data do you need to conduct a matching analysis?</p>
<ul>
<li>Panel data is necessary when conducting matching analysis. Panel data is when observations are repeated in various clusters/groups/levels.</li>
</ul>
<hr>
</section>
</section>
<section id="conduct-matching-estimation-using-the-matchit-package" class="level3">
<h3 class="anchored" data-anchor-id="conduct-matching-estimation-using-the-matchit-package">Conduct matching estimation using the {<code>MatchIt</code>} package:</h3>
<p>📜 <a href="https://kosukeimai.github.io/MatchIt/">Documentation - MatchIt</a></p>
<p>Learning goals:</p>
<ul>
<li>Approximate the Mahalanobis matching method used in Stokes (2015)</li>
<li>Implement another common matching approach called <code>propensity score matching</code></li>
</ul>
<div class="callout callout-style-simple callout-none no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><code>NOTE</code>: In the replication code associated with Stokes (2015) the {<code>AER</code>} package is used for Mahalanobis matching. In this assignment we use the {<code>MatchIt</code>} package. The results are comparable but will not be exactly the same.</p>
</div>
</div>
</div>
<hr>
</section>
<section id="c.-mahalanobis-nearest-neighbor-matching" class="level3">
<h3 class="anchored" data-anchor-id="c.-mahalanobis-nearest-neighbor-matching">2C. Mahalanobis nearest-neighbor matching</h3>
<ul>
<li>Conduct Mahalanobis matching<br>
</li>
<li>Use nearest-neighbor match without replacement using Mahalanobis distance</li>
<li>Use 1-to-1 matching (match one control unit to each treatment unit)</li>
<li>Extract the matched data using <code>match.data()</code></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2412026</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>match_model <span class="ot">&lt;-</span> <span class="fu">matchit</span>(</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Treatment_indicator ~  Pre_treatment_covariates</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    proposed_turbine_3km <span class="sc">~</span> log_home_val_07 <span class="sc">+</span> p_uni_degree <span class="sc">+</span> log_median_inc <span class="sc">+</span> log_pop_denc,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> match_data, </span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"nearest"</span>,       <span class="co"># Nearest neighbor matching</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">distance =</span> <span class="st">"mahalanobis"</span>, <span class="co"># Mahalanobis distance</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">ratio =</span> <span class="dv">1</span>,                <span class="co"># Match one control unit to one treatment unit (1:1 matching)</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">replace =</span> <span class="cn">FALSE</span>           <span class="co"># Control observations are not replaced</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract matched data</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>matched_data <span class="ot">&lt;-</span> <span class="fu">match.data</span>(match_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(match_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
matchit(formula = proposed_turbine_3km ~ log_home_val_07 + p_uni_degree + 
    log_median_inc + log_pop_denc, data = match_data, method = "nearest", 
    distance = "mahalanobis", replace = FALSE, ratio = 1)

Summary of Balance for All Data:
                Means Treated Means Control Std. Mean Diff. Var. Ratio
log_home_val_07       12.2948       12.2620          0.1138     0.5941
p_uni_degree           0.1257        0.1688         -0.5032     0.4916
log_median_inc        10.3096       10.3219         -0.0636     0.7581
log_pop_denc           3.5398        5.1192         -0.8897     0.5474
                eCDF Mean eCDF Max
log_home_val_07    0.0382   0.0881
p_uni_degree       0.1032   0.1769
log_median_inc     0.0355   0.0750
log_pop_denc       0.2099   0.3713

Summary of Balance for Matched Data:
                Means Treated Means Control Std. Mean Diff. Var. Ratio
log_home_val_07       12.2948       12.2975         -0.0093     1.0063
p_uni_degree           0.1257        0.1262         -0.0060     1.0485
log_median_inc        10.3096       10.3096          0.0002     1.0403
log_pop_denc           3.5398        3.5982         -0.0329     0.9784
                eCDF Mean eCDF Max Std. Pair Dist.
log_home_val_07    0.0075   0.0282          0.1334
p_uni_degree       0.0088   0.0367          0.1642
log_median_inc     0.0073   0.0395          0.1225
log_pop_denc       0.0109   0.0508          0.1485

Sample Sizes:
          Control Treated
All          5619     354
Matched       354     354
Unmatched    5265       0
Discarded       0       0</code></pre>
</div>
</div>
<p><strong>2C.Q1</strong> Using the <code>summary()</code> output: Which covariate had the largest and smallest <code>Std. Mean Diff.</code> before matching. Next, compare largest/smallest <code>Std. Mean Diff.</code> after matching.</p>
<ul>
<li><p>Before matching, <code>log_pop_den</code> covariate had the largest <code>Std. Mean Diff</code> and <code>log_median_inc</code> covariate had the smallest.</p></li>
<li><p>After matching, <code>log_pop_den</code> covariate had the largest <code>Std. Mean Diff</code> and <code>log_median_inc</code> covariate had the smallest.</p></li>
</ul>
<hr>
<section id="d.-create-a-love-plot-using-love.plot" class="level4">
<h4 class="anchored" data-anchor-id="d.-create-a-love-plot-using-love.plot">2D. Create a “love plot” using <code>love.plot()</code> ❤️</h4>
<p>📜 <a href="https://ngreifer.github.io/cobalt/">Documentation - cobalt</a></p>
<ul>
<li>Plot mean differences for data before &amp; after matching across all pre-treatment covariates</li>
<li>This is an effective way to evaluate how effective matching was at achieving balance.</li>
</ul>
<hr>
<ul>
<li>Make a love plot of standardized mean differences (SMDs) before vs after matching.</li>
<li>Include a threshold line at 0.1.</li>
<li>In love plot display <code>mean.diffs</code></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>new_names <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">old =</span> <span class="fu">c</span>(<span class="st">"log_home_val_07"</span>, <span class="st">"p_uni_degree"</span>, <span class="st">"log_median_inc"</span>, <span class="st">"log_pop_denc"</span>),</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">new =</span> <span class="fu">c</span>(<span class="st">"Home Value (log)"</span>, <span class="st">"Pe &lt;- rcent University Degree"</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Median Income (log)"</span>, <span class="st">"Population Density (log)"</span>))</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Love plot</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="fu">love.plot</span>(match_model, <span class="at">stats =</span> <span class="st">"mean.diffs"</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">thresholds =</span> <span class="fu">c</span>(<span class="at">m =</span> <span class="fl">0.1</span>),</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">var.names =</span> new_names)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW2_START_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>2D.Q1</strong> Interpret the love plot in your own words:</p>
<ul>
<li>Love plots visualize standardized mean differences (before and after matching). This love plot shows population density and percent university degree was imbalanced between groups before matching. After matching, all confounding variables are similar between groups, reducing bias.</li>
</ul>
<hr>
</section>
</section>
<section id="propensity-score-matching" class="level3">
<h3 class="anchored" data-anchor-id="propensity-score-matching">Propensity score matching</h3>
<hr>
<section id="e.-propensity-score-matching-psm" class="level4">
<h4 class="anchored" data-anchor-id="e.-propensity-score-matching-psm">2E. Propensity Score Matching (PSM)</h4>
<ul>
<li>Estimate 1:1 nearest-neighbor Propensity Score Matching</li>
<li>Same code as above except change <code>distance = "logit"</code></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2412026</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>propensity_scores <span class="ot">&lt;-</span> <span class="fu">matchit</span>(</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Treatment_indicator ~  Pre_treatment_covariates</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    proposed_turbine_3km <span class="sc">~</span> log_home_val_07 <span class="sc">+</span> p_uni_degree <span class="sc">+</span> log_median_inc <span class="sc">+</span> log_pop_denc,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> match_data, </span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"nearest"</span>, <span class="co"># Nearest neighbor matching</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">distance =</span> <span class="st">"logit"</span>, <span class="co"># Propensity Score Matching (PSM)</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">ratio =</span> <span class="dv">1</span>, <span class="co"># Match one control unit to one treatment unit (1:1 matching)</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">replace =</span> <span class="cn">FALSE</span> <span class="co"># Control observations are not replaced</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<hr>
</section>
<section id="create-table-displaying-covariate-balance-using-cobaltbal.tab" class="level4">
<h4 class="anchored" data-anchor-id="create-table-displaying-covariate-balance-using-cobaltbal.tab">Create table displaying covariate balance using <code>cobalt::bal.tab()</code></h4>
<p>📜 <a href="https://ngreifer.github.io/cobalt/">Documentation - cobalt</a></p>
<p>Use <code>bal.tab()</code> to report balance before and after matching.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># reporting balance from propensity_scores</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">bal.tab</span>(propensity_scores, </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">var.names =</span> new_names)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Balance Measures
                    Type Diff.Adj
distance        Distance   0.0001
log_home_val_07  Contin.   0.0205
p_uni_degree     Contin.   0.0457
log_median_inc   Contin.  -0.0042
log_pop_denc     Contin.  -0.0365

Sample sizes
          Control Treated
All          5619     354
Matched       354     354
Unmatched    5265       0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Looking at propensity_scores love plot </span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">love.plot</span>(propensity_scores, <span class="at">stats =</span> <span class="st">"mean.diffs"</span>,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">thresholds =</span> <span class="fu">c</span>(<span class="at">m =</span> <span class="fl">0.1</span>),</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">var.names =</span> new_names)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW2_START_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>2E.Q1</strong> Compare Mahalanobis vs propensity score matching. Which method did a better job at achieving balance?</p>
<ul>
<li>When comparing Mahalanobis vs propensity score <code>Std. Mean Diff.</code>, Mahalanobis did a better job of achieving balance.</li>
</ul>
<hr>
</section>
<section id="f.-estimate-an-effect-in-the-matched-sample" class="level4">
<h4 class="anchored" data-anchor-id="f.-estimate-an-effect-in-the-matched-sample">2F. Estimate an effect in the matched sample</h4>
<p>Using the matched data (Mahalanobis method), estimate the effect of treatment on the change in incumbent vote share (<code>change_liberal</code>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression: vote shares based on turbine proximity </span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>reg_match <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    change_liberal <span class="sc">~</span> proposed_turbine_3km, </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> matched_data</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summ</span>(reg_match, <span class="at">model.fit =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Observations</td>
<td style="text-align: right;">708</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Dependent variable</td>
<td style="text-align: right;">change_liberal</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Type</td>
<td style="text-align: right;">OLS linear regression</td>
</tr>
</tbody>
</table>
</div>
  
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Est.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">S.E.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t val.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">(Intercept)</td>
<td style="text-align: right;">-0.07</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">-10.96</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">proposed_turbine_3km</td>
<td style="text-align: right;">-0.06</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">-7.25</td>
<td style="text-align: right;">0.00</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> Standard errors: OLS</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</div>
<p>Coefficient Interpretations</p>
<ul>
<li>Without treatment, Liberal Party voting share is expected to average about -0.07. With treatment (proximity to wind turbines), there is an expected 0.06 decrease in Liberal Party voting shares. Standard deviation is small, and there is statistical significance in this prediction.</li>
</ul>
<p><strong>2F.Q1</strong> Have you identified a causal estimate using this approach: Why or why not?</p>
<ul>
<li>No.&nbsp;Matching only balances the <em>observed</em> covariates (home value, education, income, population density). While this improves balance and variable independence, matching does not address <em>unobserved</em> confounders that impact turbine placement and voting changes.</li>
</ul>
<p><strong>2F.Q2</strong> When using a matching method, what is the main threat to causal identification?</p>
<ul>
<li>Matching method assume there is no other systematic differences between treated and control groups other than the chosen matched variables. Unobserved variables are unaccounted for and can create bias in the outcomes, threatening causal identification reliability.</li>
</ul>
<p><strong>2F.Q3</strong> Describe why the treatment estimate represents the <code>Average Treatment for the Treated (ATT)</code> and explain why this is the case relative to estimation of the <code>Average Treatment Effect (ATE)</code>.</p>
<ul>
<li>In this study, we matched by finding one similar control unit for each treated unit. Therefore, while all treated units are included, only some of the control units were included in the <code>match_model</code>. ATT focuses on the average effect of the treated based on those who received treatment. Because the model includes all treatment groups, the estimatations represent the ATT. On the other hand, ATE measures the average effect of a treatment across the entire population. Because the model does not include the entire population, <code>match_model</code> does not estimate the ATE.</li>
</ul>
<hr>
</section>
</section>
<section id="part-3-panel-data-fixed-effects-and-difference-in-difference" class="level3">
<h3 class="anchored" data-anchor-id="part-3-panel-data-fixed-effects-and-difference-in-difference">Part 3: Panel Data, Fixed Effects, and Difference-in-Difference</h3>
<p><strong>Data source:</strong> <a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/SDUGCC">Dataverse-Stokes2015</a></p>
<hr>
<section id="a-read-in-the-panel-data-code-variables-precinct_id-and-year-as-factors" class="level4">
<h4 class="anchored" data-anchor-id="a-read-in-the-panel-data-code-variables-precinct_id-and-year-as-factors"><strong>3A:</strong> Read in the panel data + code variables <code>precinct_id</code> and <code>year</code> as factors</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in data </span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>panel_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"Stokes15_panel_data.csv"</span>))</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># HINT: Try running `tabyl(panel_data$year)`. Review article to make sense of the row numbers (n).</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tabyl</span>(panel_data<span class="sc">$</span>year)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> panel_data$year    n   percent
            2003 6186 0.3333333
            2007 6186 0.3333333
            2011 6186 0.3333333</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Year and precinct_id as factor </span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>panel_data<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(panel_data<span class="sc">$</span>year)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>panel_data<span class="sc">$</span>precinct_id <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(panel_data<span class="sc">$</span>precinct_id)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>3A.Q1:</strong> Why are there 18,558 rows in <code>panel_data</code>?</p>
<ul>
<li><p>There are a total of 6186 precincts that have repeating measurementss (voting shares) for 3 different years (2003, 2007, 2011).</p></li>
<li><p>6186 * 3 = 18,558</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># How many years are included in the panel? - 3 years: 2003, 2007, 2011</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(panel_data<span class="sc">$</span>year)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2003 2007 2011
Levels: 2003 2007 2011</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># How many precincts are there? - 6186 </span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(panel_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [18,558 × 14] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ precinct_id        : Factor w/ 6186 levels "10.001.10.1.",..: 1 1 1 2 2 2 3 3 3 4 ...
 $ year               : Factor w/ 3 levels "2003","2007",..: 1 2 3 1 2 3 1 2 3 1 ...
 $ perc_lib           : num [1:18558] 0.434 0.216 0.301 0.434 0.169 ...
 $ proposed_turbine   : num [1:18558] 0 0 0 0 0 0 0 0 0 0 ...
 $ operational_turbine: num [1:18558] 0 0 0 0 0 0 0 0 0 0 ...
 $ log_pop            : num [1:18558] 5.81 3.91 3.86 5.2 2.15 ...
 $ log_pop_denc       : num [1:18558] -1.473 -1.278 -1.793 -2.082 0.199 ...
 $ log_median_inc     : num [1:18558] 9.96 9.75 10.29 9.96 9.7 ...
 $ log_home_val       : num [1:18558] 11.8 12.3 12.8 11.9 12.3 ...
 $ avg_home_val       : num [1:18558] 135101 215331 359354 142830 215782 ...
 $ unemploy_rate      : num [1:18558] 5.26 11.21 12.8 5.86 14.31 ...
 $ p_uni_degree       : num [1:18558] 0.251 0.196 0.192 0.266 0.176 ...
 $ p_immigrant        : num [1:18558] 0.153 0.117 0.129 0.168 0.079 ...
 $ p_housing_own      : num [1:18558] 0.665 0.933 0.941 0.667 0.918 ...
 - attr(*, "spec")=
  .. cols(
  ..   precinct_id = col_character(),
  ..   year = col_double(),
  ..   perc_lib = col_double(),
  ..   proposed_turbine = col_double(),
  ..   operational_turbine = col_double(),
  ..   log_pop = col_double(),
  ..   log_pop_denc = col_double(),
  ..   log_median_inc = col_double(),
  ..   log_home_val = col_double(),
  ..   avg_home_val = col_double(),
  ..   unemploy_rate = col_double(),
  ..   p_uni_degree = col_double(),
  ..   p_immigrant = col_double(),
  ..   p_housing_own = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
</div>
<p><strong>3A.Q2:</strong> How many unique precincts are <em>ever treated</em> (i.e., <code>proposed</code> &amp; <code>operational</code>)?</p>
<ul>
<li>Of the treatment precincts, 184 had proposed turbines and 52 had operational turbines.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>panel_data <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(precinct_id) <span class="sc">%&gt;%</span> <span class="co"># Grouping for each precincts</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>( <span class="co"># seperating prosposed vs operational turbines </span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">ever_proposed    =</span> <span class="fu">any</span>(proposed_turbine <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">ever_operational =</span> <span class="fu">any</span>(operational_turbine <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>( <span class="co"># Total count </span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_ever_proposed    =</span> <span class="fu">sum</span>(ever_proposed),</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_ever_operational =</span> <span class="fu">sum</span>(ever_operational))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  n_ever_proposed n_ever_operational
            &lt;int&gt;              &lt;int&gt;
1             184                 52</code></pre>
</div>
</div>
<hr>
</section>
<section id="b.-plot-and-evaluate-parallel-trends-replicate-figure.2-stokes-2015" class="level4">
<h4 class="anchored" data-anchor-id="b.-plot-and-evaluate-parallel-trends-replicate-figure.2-stokes-2015"><strong>3B.</strong> Plot and evaluate parallel trends: Replicate <code>Figure.2</code> (Stokes, 2015)</h4>
<ol type="1">
<li>Create indicators for whether each precinct is ever treated by 2011 (<code>treat_p</code>, <code>treat_o</code>; separate indicator for proposals and operational turbines).</li>
<li>Plot mean incumbent vote share by year for treated vs control precincts (with 95% CIs).</li>
<li>Facet by turbine type (proposed &amp; operational)</li>
</ol>
<p>Step 1: Prepare data</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Indicators: control vs treatment group (treatment: `treat_o` vs `treat_p`)</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>trends_data <span class="ot">&lt;-</span> panel_data <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(precinct_id) <span class="sc">%&gt;%</span> <span class="co"># group by precinct </span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>( </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">treat_p =</span> <span class="fu">as.integer</span>(<span class="fu">any</span>(proposed_turbine <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),  <span class="co"># ever proposed (in any year)</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">treat_o =</span> <span class="fu">as.integer</span>(<span class="fu">any</span>(operational_turbine <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))) <span class="sc">%&gt;%</span> <span class="co"># ever operational (in any year)</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">c</span>(treat_p, treat_o), <span class="co"># new col `turbine_type` - with treat_p and treat_o</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"turbine_type"</span>, <span class="at">values_to =</span> <span class="st">"treat"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>( <span class="co"># Make `turbine_type` a factor </span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">turbine_type =</span> <span class="fu">factor</span>(turbine_type,</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>                            <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"treat_p"</span>, <span class="st">"treat_o"</span>),</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>                            <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Proposed turbines"</span>, <span class="st">"Operational turbines"</span>)),  </span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">status =</span> <span class="fu">if_else</span>(treat <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Treated"</span>, <span class="st">"Control"</span>), <span class="co"># control and treatment col </span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">year   =</span> <span class="fu">factor</span>(year)) <span class="co"># Making sure year is a factor </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Step 2: Create trends plot</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>pd <span class="ot">&lt;-</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.15</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>trends_data <span class="sc">%&gt;%</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(turbine_type, status, year) <span class="sc">%&gt;%</span> <span class="co"># Grouping Group (T vs C), year, and Treatment type (operational vs proposed)</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>( </span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(perc_lib, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="co"># mean of voting share</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">n    =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(perc_lib)), <span class="co"># count </span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">se   =</span> <span class="fu">sd</span>(perc_lib, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> <span class="fu">sqrt</span>(n), <span class="co"># Standard error </span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">ci   =</span> <span class="fu">qt</span>(.<span class="dv">975</span>, <span class="at">df =</span> <span class="fu">pmax</span>(n <span class="sc">-</span> <span class="dv">1</span>, <span class="dv">1</span>)) <span class="sc">*</span> se, <span class="co"># Confidence intervals </span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(year, mean, <span class="at">color =</span> status, <span class="at">group =</span> status)) <span class="sc">+</span> <span class="co"># PLOT! </span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">position =</span> pd, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span> <span class="co"># line plot with points </span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">position =</span> pd, <span class="at">size =</span> <span class="fl">2.6</span>) <span class="sc">+</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>( <span class="co"># CI </span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">ymin =</span> mean <span class="sc">-</span> ci, <span class="at">ymax =</span> mean <span class="sc">+</span> ci),</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">position =</span> pd, <span class="at">width =</span> .<span class="dv">12</span>, <span class="at">linewidth =</span> .<span class="dv">7</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> turbine_type, <span class="at">nrow =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co"># 2 plots - opertaional vs proposed turbines </span></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="at">Control =</span> <span class="st">"#0072B2"</span>, <span class="at">Treated =</span> <span class="st">"#B22222"</span>)) <span class="sc">+</span></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> <span class="fu">percent_format</span>(<span class="at">accuracy =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(.<span class="dv">20</span>, .<span class="dv">57</span>)) <span class="sc">+</span></span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Figure 2. Trends in the Governing Party’s Vote Share"</span>,</span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Election Year"</span>,</span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Liberal Party Vote Share"</span>,</span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"bottom"</span>,</span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW2_START_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>3B.Q1:</strong> Write a short paragraph assessing the parallel trends assumption for each outcome.</p>
<ul>
<li><p>Background: In this study, pre-treatment is considered the 2003 voting shares. In 2006, the FIT policy was initated on a small scale. Therefore, early turbines proposals and operations began in 2007. In 2009, the law that refused communities to reject renewable energy started. Full effects of the 2009 Green Energy Act were seen in 2011.</p></li>
<li><p>The graph above shows parallel trends between treatment and control groups in 2003 and 2007 (the baseline and early stages of the intervention). Treatment effect is exemplified in the treatment groups change of Liberal Party voting shares in 2011. Thus, the parallel trend assumption is met, but should be considered with caution due to the limited pre-treatment measurements. One pre-treatment measurement and one early-intervention stage measurement, its not enough observations to be super confident on meeting the parallel trends assumption.</p></li>
</ul>
<hr>
</section>
</section>
<section id="estimating-fixed-effects-models-did-for-proposals" class="level3">
<h3 class="anchored" data-anchor-id="estimating-fixed-effects-models-did-for-proposals">Estimating Fixed Effects Models (DiD) for proposals</h3>
<p><span class="math display">\[
\text{Y}_{it}
=  \alpha_0 +
\beta \cdot (\text{proposed_turbine}_{it})
+ \gamma_i
+ \delta_t
+ \varepsilon_{it}
\]</span></p>
<ul>
<li><span class="math inline">\(Y_{it}\)</span> is the vote share for the Liberal Party in precinct <em>i</em> in time <em>t</em></li>
<li><span class="math inline">\(\beta\)</span> is the treatment effect of a turbine being proposed within a precinct</li>
<li><span class="math inline">\(\gamma_i\)</span> is the precinct fixed effect</li>
<li><span class="math inline">\(\delta_t\)</span> is the year fixed effect</li>
</ul>
<hr>
</section>
<section id="example-1-randomly-sample-40-precincts" class="level3">
<h3 class="anchored" data-anchor-id="example-1-randomly-sample-40-precincts">Example 1: Randomly sample 40 precincts</h3>
<ul>
<li>To illustrate the “dummy variable method” of estimating fixed effects using the the general <code>lm()</code> function we are going to randomly sample 40 precincts (20 “treated” precincts with proposed turbines).</li>
<li>If we attempted to use this approach with the full sample estimating all 6185 (n-1) precinct-level coefficients is impractical (it would take a long time).</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">40002026</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Dataframe of just precinct_id and if have proposed_turbine</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>precinct_frame <span class="ot">&lt;-</span> panel_data <span class="sc">%&gt;%</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(precinct_id) <span class="sc">%&gt;%</span> </span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>( <span class="co"># where proposed_turbine = 1 =&gt; TRUE --&gt; convert results to an integers (0,1)</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">proposed_turbine_any =</span> <span class="fu">as.integer</span>(<span class="fu">any</span>(proposed_turbine <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Randomly selecting 20 precinct_ids </span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>ids_40 <span class="ot">&lt;-</span> precinct_frame <span class="sc">%&gt;%</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(proposed_turbine_any) <span class="sc">%&gt;%</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">20</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(precinct_id)</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the panel_data for the randomly selected rows </span></span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>sample_40_precincts <span class="ot">&lt;-</span> panel_data <span class="sc">%&gt;%</span></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">semi_join</span>(ids_40, <span class="at">by =</span> <span class="st">"precinct_id"</span>) <span class="co"># semi_join: return all rows from x with a match in y.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<hr>
<section id="c-estimate-a-fixed-effects-model-using-lm-with-fixed-effects-added-for-precinct-and-year-using-the-sample-of-40-precincts-just-created." class="level4">
<h4 class="anchored" data-anchor-id="c-estimate-a-fixed-effects-model-using-lm-with-fixed-effects-added-for-precinct-and-year-using-the-sample-of-40-precincts-just-created."><strong>3C:</strong> Estimate a fixed effects model using <code>lm()</code> with fixed effects added for <code>precinct</code> and <code>year</code> using the sample of 40 precincts just created.</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># lm model with precinct and year as fixed </span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>model1_ff <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    perc_lib <span class="sc">~</span> proposed_turbine <span class="sc">+</span> precinct_id <span class="sc">+</span> year,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> sample_40_precincts </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summ</span>(model1_ff, <span class="at">model.fit =</span> <span class="cn">FALSE</span>, <span class="at">digits =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Observations</td>
<td style="text-align: right;">120</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Dependent variable</td>
<td style="text-align: right;">perc_lib</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Type</td>
<td style="text-align: right;">OLS linear regression</td>
</tr>
</tbody>
</table>
</div>
  
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Est.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">S.E.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t val.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">(Intercept)</td>
<td style="text-align: right;">0.275</td>
<td style="text-align: right;">0.050</td>
<td style="text-align: right;">5.460</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">proposed_turbine</td>
<td style="text-align: right;">-0.057</td>
<td style="text-align: right;">0.031</td>
<td style="text-align: right;">-1.858</td>
<td style="text-align: right;">0.067</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id10.115s.10.84.</td>
<td style="text-align: right;">0.166</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">2.402</td>
<td style="text-align: right;">0.019</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id105.038.105.45.</td>
<td style="text-align: right;">0.053</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">0.765</td>
<td style="text-align: right;">0.447</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id14.149.14.79.</td>
<td style="text-align: right;">0.208</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">2.976</td>
<td style="text-align: right;">0.004</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id14.168.14.82.</td>
<td style="text-align: right;">0.192</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">2.749</td>
<td style="text-align: right;">0.007</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id18.003.18.1.</td>
<td style="text-align: right;">0.121</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">1.738</td>
<td style="text-align: right;">0.086</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id18.033.18.19.</td>
<td style="text-align: right;">-0.002</td>
<td style="text-align: right;">0.072</td>
<td style="text-align: right;">-0.034</td>
<td style="text-align: right;">0.973</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id21.126.21.179.</td>
<td style="text-align: right;">0.204</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">2.950</td>
<td style="text-align: right;">0.004</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id22.061.22.60.</td>
<td style="text-align: right;">0.213</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">3.047</td>
<td style="text-align: right;">0.003</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id22.124.22.52.</td>
<td style="text-align: right;">0.156</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">2.230</td>
<td style="text-align: right;">0.029</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id22.137.22.193.</td>
<td style="text-align: right;">0.179</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">2.590</td>
<td style="text-align: right;">0.011</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id22.158.22.203.</td>
<td style="text-align: right;">0.165</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">2.357</td>
<td style="text-align: right;">0.021</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id22.209.22.172.</td>
<td style="text-align: right;">0.188</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">2.699</td>
<td style="text-align: right;">0.009</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id28.056.28.149.</td>
<td style="text-align: right;">-0.011</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">-0.160</td>
<td style="text-align: right;">0.873</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id28.072.28.98.</td>
<td style="text-align: right;">0.097</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">1.409</td>
<td style="text-align: right;">0.163</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id28.139.28.145.</td>
<td style="text-align: right;">0.040</td>
<td style="text-align: right;">0.072</td>
<td style="text-align: right;">0.553</td>
<td style="text-align: right;">0.582</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id28.163.28.69.</td>
<td style="text-align: right;">0.124</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">1.802</td>
<td style="text-align: right;">0.075</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id29.241.29.172.</td>
<td style="text-align: right;">0.067</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">0.958</td>
<td style="text-align: right;">0.341</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id34.050.34.39.</td>
<td style="text-align: right;">0.342</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">4.947</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id34.151.34.125.</td>
<td style="text-align: right;">0.098</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">1.399</td>
<td style="text-align: right;">0.166</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id36.133.36.92.</td>
<td style="text-align: right;">0.358</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">5.179</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id40.044.40.68.</td>
<td style="text-align: right;">0.236</td>
<td style="text-align: right;">0.072</td>
<td style="text-align: right;">3.275</td>
<td style="text-align: right;">0.002</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id40.098.40.120.</td>
<td style="text-align: right;">0.195</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">2.792</td>
<td style="text-align: right;">0.007</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id40.134.40.174.</td>
<td style="text-align: right;">0.216</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">3.127</td>
<td style="text-align: right;">0.002</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id40.243.40.22.</td>
<td style="text-align: right;">0.325</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">4.651</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id40.244.40.46.</td>
<td style="text-align: right;">0.178</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">2.543</td>
<td style="text-align: right;">0.013</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id55.228.55.180.</td>
<td style="text-align: right;">0.130</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">1.883</td>
<td style="text-align: right;">0.064</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id58.162.58.98.</td>
<td style="text-align: right;">0.278</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">4.024</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id58.232.58.231.</td>
<td style="text-align: right;">0.203</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">2.940</td>
<td style="text-align: right;">0.004</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id67.141.67.123.</td>
<td style="text-align: right;">0.022</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">0.311</td>
<td style="text-align: right;">0.757</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id69.073.69.35.</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">1.015</td>
<td style="text-align: right;">0.313</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id70.081.70.44.</td>
<td style="text-align: right;">0.062</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">0.899</td>
<td style="text-align: right;">0.372</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id70.135.70.105.</td>
<td style="text-align: right;">0.441</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">6.388</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id70.221.70.155.</td>
<td style="text-align: right;">0.247</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">3.576</td>
<td style="text-align: right;">0.001</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id73.248.73.180.</td>
<td style="text-align: right;">0.187</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">2.672</td>
<td style="text-align: right;">0.009</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id73.251.73.180.</td>
<td style="text-align: right;">0.204</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">2.927</td>
<td style="text-align: right;">0.005</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id87.017.87.58.</td>
<td style="text-align: right;">0.127</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">1.836</td>
<td style="text-align: right;">0.070</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id87.053.87.68.</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">3.100</td>
<td style="text-align: right;">0.003</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id87.213.87.24.</td>
<td style="text-align: right;">0.033</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">0.469</td>
<td style="text-align: right;">0.641</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id98.009.98.12.</td>
<td style="text-align: right;">0.129</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">1.868</td>
<td style="text-align: right;">0.066</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">year2007</td>
<td style="text-align: right;">-0.045</td>
<td style="text-align: right;">0.019</td>
<td style="text-align: right;">-2.364</td>
<td style="text-align: right;">0.021</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">year2011</td>
<td style="text-align: right;">-0.131</td>
<td style="text-align: right;">0.024</td>
<td style="text-align: right;">-5.381</td>
<td style="text-align: right;">0.000</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> Standard errors: OLS</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summ</span>(model1_ff, <span class="at">model.fit =</span> <span class="cn">FALSE</span>, <span class="at">digits =</span> <span class="dv">3</span>, <span class="at">robust =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Observations</td>
<td style="text-align: right;">120</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Dependent variable</td>
<td style="text-align: right;">perc_lib</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Type</td>
<td style="text-align: right;">OLS linear regression</td>
</tr>
</tbody>
</table>
</div>
  
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Est.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">S.E.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t val.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">(Intercept)</td>
<td style="text-align: right;">0.275</td>
<td style="text-align: right;">0.085</td>
<td style="text-align: right;">3.247</td>
<td style="text-align: right;">0.002</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">proposed_turbine</td>
<td style="text-align: right;">-0.057</td>
<td style="text-align: right;">0.039</td>
<td style="text-align: right;">-1.465</td>
<td style="text-align: right;">0.147</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id10.115s.10.84.</td>
<td style="text-align: right;">0.166</td>
<td style="text-align: right;">0.101</td>
<td style="text-align: right;">1.646</td>
<td style="text-align: right;">0.104</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id105.038.105.45.</td>
<td style="text-align: right;">0.053</td>
<td style="text-align: right;">0.104</td>
<td style="text-align: right;">0.509</td>
<td style="text-align: right;">0.612</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id14.149.14.79.</td>
<td style="text-align: right;">0.208</td>
<td style="text-align: right;">0.094</td>
<td style="text-align: right;">2.201</td>
<td style="text-align: right;">0.031</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id14.168.14.82.</td>
<td style="text-align: right;">0.192</td>
<td style="text-align: right;">0.110</td>
<td style="text-align: right;">1.751</td>
<td style="text-align: right;">0.084</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id18.003.18.1.</td>
<td style="text-align: right;">0.121</td>
<td style="text-align: right;">0.107</td>
<td style="text-align: right;">1.132</td>
<td style="text-align: right;">0.261</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id18.033.18.19.</td>
<td style="text-align: right;">-0.002</td>
<td style="text-align: right;">0.101</td>
<td style="text-align: right;">-0.024</td>
<td style="text-align: right;">0.981</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id21.126.21.179.</td>
<td style="text-align: right;">0.204</td>
<td style="text-align: right;">0.157</td>
<td style="text-align: right;">1.299</td>
<td style="text-align: right;">0.198</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id22.061.22.60.</td>
<td style="text-align: right;">0.213</td>
<td style="text-align: right;">0.105</td>
<td style="text-align: right;">2.023</td>
<td style="text-align: right;">0.047</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id22.124.22.52.</td>
<td style="text-align: right;">0.156</td>
<td style="text-align: right;">0.103</td>
<td style="text-align: right;">1.509</td>
<td style="text-align: right;">0.135</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id22.137.22.193.</td>
<td style="text-align: right;">0.179</td>
<td style="text-align: right;">0.104</td>
<td style="text-align: right;">1.721</td>
<td style="text-align: right;">0.089</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id22.158.22.203.</td>
<td style="text-align: right;">0.165</td>
<td style="text-align: right;">0.088</td>
<td style="text-align: right;">1.879</td>
<td style="text-align: right;">0.064</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id22.209.22.172.</td>
<td style="text-align: right;">0.188</td>
<td style="text-align: right;">0.106</td>
<td style="text-align: right;">1.770</td>
<td style="text-align: right;">0.081</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id28.056.28.149.</td>
<td style="text-align: right;">-0.011</td>
<td style="text-align: right;">0.112</td>
<td style="text-align: right;">-0.099</td>
<td style="text-align: right;">0.921</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id28.072.28.98.</td>
<td style="text-align: right;">0.097</td>
<td style="text-align: right;">0.104</td>
<td style="text-align: right;">0.934</td>
<td style="text-align: right;">0.353</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id28.139.28.145.</td>
<td style="text-align: right;">0.040</td>
<td style="text-align: right;">0.111</td>
<td style="text-align: right;">0.359</td>
<td style="text-align: right;">0.721</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id28.163.28.69.</td>
<td style="text-align: right;">0.124</td>
<td style="text-align: right;">0.106</td>
<td style="text-align: right;">1.179</td>
<td style="text-align: right;">0.242</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id29.241.29.172.</td>
<td style="text-align: right;">0.067</td>
<td style="text-align: right;">0.089</td>
<td style="text-align: right;">0.749</td>
<td style="text-align: right;">0.456</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id34.050.34.39.</td>
<td style="text-align: right;">0.342</td>
<td style="text-align: right;">0.089</td>
<td style="text-align: right;">3.821</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id34.151.34.125.</td>
<td style="text-align: right;">0.098</td>
<td style="text-align: right;">0.093</td>
<td style="text-align: right;">1.050</td>
<td style="text-align: right;">0.297</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id36.133.36.92.</td>
<td style="text-align: right;">0.358</td>
<td style="text-align: right;">0.091</td>
<td style="text-align: right;">3.941</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id40.044.40.68.</td>
<td style="text-align: right;">0.236</td>
<td style="text-align: right;">0.096</td>
<td style="text-align: right;">2.457</td>
<td style="text-align: right;">0.016</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id40.098.40.120.</td>
<td style="text-align: right;">0.195</td>
<td style="text-align: right;">0.092</td>
<td style="text-align: right;">2.123</td>
<td style="text-align: right;">0.037</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id40.134.40.174.</td>
<td style="text-align: right;">0.216</td>
<td style="text-align: right;">0.090</td>
<td style="text-align: right;">2.399</td>
<td style="text-align: right;">0.019</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id40.243.40.22.</td>
<td style="text-align: right;">0.325</td>
<td style="text-align: right;">0.098</td>
<td style="text-align: right;">3.314</td>
<td style="text-align: right;">0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id40.244.40.46.</td>
<td style="text-align: right;">0.178</td>
<td style="text-align: right;">0.095</td>
<td style="text-align: right;">1.873</td>
<td style="text-align: right;">0.065</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id55.228.55.180.</td>
<td style="text-align: right;">0.130</td>
<td style="text-align: right;">0.092</td>
<td style="text-align: right;">1.406</td>
<td style="text-align: right;">0.164</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id58.162.58.98.</td>
<td style="text-align: right;">0.278</td>
<td style="text-align: right;">0.097</td>
<td style="text-align: right;">2.867</td>
<td style="text-align: right;">0.005</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id58.232.58.231.</td>
<td style="text-align: right;">0.203</td>
<td style="text-align: right;">0.092</td>
<td style="text-align: right;">2.203</td>
<td style="text-align: right;">0.031</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id67.141.67.123.</td>
<td style="text-align: right;">0.022</td>
<td style="text-align: right;">0.115</td>
<td style="text-align: right;">0.189</td>
<td style="text-align: right;">0.850</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id69.073.69.35.</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">0.104</td>
<td style="text-align: right;">0.677</td>
<td style="text-align: right;">0.500</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id70.081.70.44.</td>
<td style="text-align: right;">0.062</td>
<td style="text-align: right;">0.095</td>
<td style="text-align: right;">0.655</td>
<td style="text-align: right;">0.514</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id70.135.70.105.</td>
<td style="text-align: right;">0.441</td>
<td style="text-align: right;">0.128</td>
<td style="text-align: right;">3.451</td>
<td style="text-align: right;">0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id70.221.70.155.</td>
<td style="text-align: right;">0.247</td>
<td style="text-align: right;">0.111</td>
<td style="text-align: right;">2.217</td>
<td style="text-align: right;">0.030</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id73.248.73.180.</td>
<td style="text-align: right;">0.187</td>
<td style="text-align: right;">0.108</td>
<td style="text-align: right;">1.720</td>
<td style="text-align: right;">0.089</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id73.251.73.180.</td>
<td style="text-align: right;">0.204</td>
<td style="text-align: right;">0.102</td>
<td style="text-align: right;">1.995</td>
<td style="text-align: right;">0.050</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id87.017.87.58.</td>
<td style="text-align: right;">0.127</td>
<td style="text-align: right;">0.112</td>
<td style="text-align: right;">1.135</td>
<td style="text-align: right;">0.260</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id87.053.87.68.</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">0.150</td>
<td style="text-align: right;">1.428</td>
<td style="text-align: right;">0.157</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">precinct_id87.213.87.24.</td>
<td style="text-align: right;">0.033</td>
<td style="text-align: right;">0.087</td>
<td style="text-align: right;">0.375</td>
<td style="text-align: right;">0.709</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">precinct_id98.009.98.12.</td>
<td style="text-align: right;">0.129</td>
<td style="text-align: right;">0.107</td>
<td style="text-align: right;">1.210</td>
<td style="text-align: right;">0.230</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">year2007</td>
<td style="text-align: right;">-0.045</td>
<td style="text-align: right;">0.024</td>
<td style="text-align: right;">-1.876</td>
<td style="text-align: right;">0.064</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">year2011</td>
<td style="text-align: right;">-0.131</td>
<td style="text-align: right;">0.036</td>
<td style="text-align: right;">-3.686</td>
<td style="text-align: right;">0.000</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> Standard errors: Robust, type = HC3</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</div>
<p><strong>3C.Q1:</strong> Intuition check: Is the <em>signal-to-noise</em> ratio for the treatment estimate greater than <em>2-to-1</em>?</p>
<ul>
<li><p>For the treatment estimate, the <em>signal-to-noise</em> ratio is less than the 2-to-1 threshold. The treatment effect is marginally significant (p = 0.067) and the estimate is twice as large as its standard error. Meaning there is signal but it is noisy with moderate uncertainty.</p></li>
<li><p>|estimate| / standard error = |-0.057| / 0.031 = 1.83871</p></li>
</ul>
<blockquote class="blockquote">
<p>HINT: Add the argument <code>digits = 3</code> to the <code>summ()</code> function above</p>
</blockquote>
<p><strong>3C.Q2:</strong> Re-run the <code>summ()</code> function using the <em>heteroscedasticiy robust standard error adjustment</em> (<code>robust = TRUE</code>). Did the standard error (S.E.) estimates change? Explain why.</p>
<ul>
<li><p>The standard error increases (0.031 –&gt; 0.039) and the p-value increases (0.067 –&gt; 0.147). With the <em>heteroscedasticiy robust standard error adjustment,</em> the treatment effect has greater variance and is non-significant.</p></li>
<li><p>The OLS standard error assumes homoscedasticity, where the variance of errors is constant across all observations. When relaxing that assumption with <code>robust = TRUE</code>, the variance can differ across observations. For instance, Liberal vote share can now vary between treated vs.&nbsp;control precincts, different precincts over time, and different election years.</p></li>
<li><p>The OLS did not account for heteroscedasticity which led to overconfident inference.</p></li>
</ul>
<p><strong>3C.Q3:</strong> Compare results of the model above to the findings from the fixed effects analysis in the Stokes (2015) study. Why might the results be similar or different?</p>
<ul>
<li>Both the model above and Stokes (2015) study show a decline in Liberal voting shares in relation to proposed turbine implementation in precincts. However, the model above has larger uncertainty and no statistical significance. The models main difference is the sample size. Stokes model includes 18,558 observations (6,186 precincts for 3 years), whereas my model only includes 120 observations (40 precincts for 3 years ). While the model above is consistent with the patterns in Stokes model, the small sample decreases the model’s statistical power and increases uncertainty.</li>
</ul>
<p><strong>3C.Q4:</strong> In your own words, explain why it is advantageous from a causal inference perspective to include year and precinct fixed effects. Explain how between-level and within-level variance is relevant to the problem of omitted variable bias (OVB).</p>
<ul>
<li>Adding precinct as a fixed effect controls for all the possible time-invariant confounding differences between precincts, such as demographic, geographic, and pre-existing beliefs. Adding year as a fix effect controls for differences/trends that happened between 2003, 2007, and 2011 that effected all precincts equally. Adding fixed effects that help control between-level variance (differences across precincts) and within-level variance (changes within the same precinct over time) allow for unobserved and observed differences in the parameters to be “differenced out”, reducing OVB.</li>
</ul>
<hr>
</section>
<section id="d.-now-using-the-full-sample-estimate-the-treatment-effect-of-wind-turbine-proposals-on-incumbent-vote-share.-use-feols-from-the-fixest-package-to-estimate-the-fixed-effects." class="level4">
<h4 class="anchored" data-anchor-id="d.-now-using-the-full-sample-estimate-the-treatment-effect-of-wind-turbine-proposals-on-incumbent-vote-share.-use-feols-from-the-fixest-package-to-estimate-the-fixed-effects."><strong>3D.</strong> Now using the full sample, estimate the treatment effect of wind turbine proposals on incumbent vote share. Use <code>feols()</code> from the <code>{fixest}</code> package to estimate the fixed effects.</h4>
<p>See vignette here: <a href="https://cran.r-project.org/web/packages/fixest/vignettes/fixest_walkthrough.html#11_Estimation">fixest walkthrough</a></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>model2_ff <span class="ot">&lt;-</span>  <span class="fu">feols</span>(</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>    perc_lib <span class="sc">~</span> proposed_turbine <span class="sc">|</span> year <span class="sc">+</span> precinct_id, <span class="co"># Add fixed effects </span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> panel_data, </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">cluster =</span> <span class="sc">~</span>precinct_id <span class="co"># cluster by precinct_id </span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2_ff, <span class="at">model.fit =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: perc_lib
Observations: 18,558
Fixed-effects: year: 3,  precinct_id: 6,186
Standard-errors: Clustered (precinct_id) 
                 Estimate Std. Error  t value   Pr(&gt;|t|)    
proposed_turbine -0.04157   0.007682 -5.41144 6.4869e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 0.070481     Adj. R2: 0.624835
                 Within R2: 0.00224 </code></pre>
</div>
</div>
<p><strong>3D.Q1:</strong> Interpret the model results and translate findings to be clear to an audience that may not have a background in causal inference (Econometrics) methods.</p>
<p>In panel data settings, why is clustering by precinct important (i.e., <code>cluster = ~precinct_id</code>) ?”</p>
<ul>
<li><p>In this study, we are investigating if communities near wind turbines turned against the Liberal government that approved them. To understand the <em>change</em> of voting behavior, we compared precincts to themselves over time. We found that precincts with proposed wind turbines had a 4.157% decrease of Liberal Party vote shares, which shows local voter backlash.</p></li>
<li><p>A single precinct’s voting trends over the years are correlated. For instances, how a community votes in 2003 is correlated to their votes in 2007. Clustering by precinct accounts for this within-precinct correlation.</p></li>
</ul>
<hr>
</section>
<section id="e.-estimate-the-treatment-effect-of-operational-wind-turbines-on-incumbent-vote-share.-use-the-same-approach-as-the-previous-model." class="level4">
<h4 class="anchored" data-anchor-id="e.-estimate-the-treatment-effect-of-operational-wind-turbines-on-incumbent-vote-share.-use-the-same-approach-as-the-previous-model."><strong>3E.</strong> Estimate the treatment effect of <em>operational wind turbines</em> on incumbent vote share. Use the same approach as the previous model.</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>model3_ff <span class="ot">&lt;-</span>  <span class="fu">feols</span>(</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    perc_lib <span class="sc">~</span> operational_turbine <span class="sc">|</span> year <span class="sc">+</span> precinct_id, <span class="co"># Add fixed effects </span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> panel_data, </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">cluster =</span> <span class="sc">~</span>precinct_id <span class="co"># cluster by precinct_id </span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3_ff, <span class="at">model.fit =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: perc_lib
Observations: 18,558
Fixed-effects: year: 3,  precinct_id: 6,186
Standard-errors: Clustered (precinct_id) 
                     Estimate Std. Error  t value   Pr(&gt;|t|)    
operational_turbine -0.092762   0.011739 -7.90195 3.2271e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 0.070447     Adj. R2: 0.625198
                 Within R2: 0.003206</code></pre>
</div>
</div>
<p><strong>3E.Q1:</strong> Interpret the <code>model3_ff</code> results as clearly and <strong>concisely</strong> as you can.</p>
<ul>
<li>Precincts with operational wind turbines had approximately a 9.276% decrease of Liberal Party vote shares compared to what would have happened without the turbines, which shows local voter backlash.</li>
</ul>
<p><strong>3E.Q2:</strong> Why do you think the effect of proposed wind turbines is different from operational wind turbines. Develop your own theory about why incumbent vote share is affected in this way. Use the Stokes (2015) study to inform your response as needed.</p>
<ul>
<li>Physically having to deal with wind turbines in your communities is drastically different than possibly/planning to have turbines in your community. Communities that actually deal with wind turbines everyday have a larger grudge with Liberal Party, which leads to a larger reduction in Liberal Party voting shares.</li>
</ul>
<hr>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>